name: Doko Docker CI

on:
  push:
    branches:
      - main

env:
  DK_CONTAINER: dokocli/doko
  DK_FULL_CONTAINER: dokocli/doko-full

jobs:
  # Doko Container Docker Image `dokocli/doko`
  dk_container_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Doko Container
        run: |
          docker pull $DK_CONTAINER:latest
          docker build -t $DK_CONTAINER --cache-from $DK_CONTAINER:latest .
          docker push $DK_CONTAINER

  dk_container_run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run doko in docker container
        run: docker run --rm -iv /var/run/docker.sock:/var/run/docker.sock $DK_CONTAINER -h

  # Doko Full Container Docker Image `dokocli/doko-full`
  dk_full_container_build:
    needs: [ dk_container_build, dk_container_run]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Doko Full Container
        run: |
          docker pull $DK_FULL_CONTAINER:latest
          docker build -t $DK_FULL_CONTAINER --cache-from $DK_FULL_CONTAINER:latest .
          docker push $DK_FULL_CONTAINER
